# Generated by Django 4.0.3 on 2022-06-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buddies", "0012_voter_absentee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="buddies.voter"
                    ),
                ),
            ],
        ),
    ]
