# Generated by Django 4.0.5 on 2022-06-24 23:46

import django.db.models.deletion
from django.db import migrations

import annoying.fields


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0012_voter_absentee"),
        ("alerts", "0002_profile_last"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="voter",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="friends.voter"
            ),
        ),
    ]
