# Generated by Django 4.0.5 on 2022-06-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0004_profile_should_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="never_alert",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="should_alert",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
