# Generated by Django 4.0.5 on 2022-06-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0006_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-sent_at", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["last_alerted", "last_viewed"]},
        ),
    ]
