# Generated by Django 4.0.5 on 2022-06-29 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0008_profile_staleness"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-staleness"]},
        ),
    ]
