# Generated by Django 4.0.5 on 2022-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0009_reverse_staleness"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
