# Generated by Django 4.0.5 on 2022-07-09 19:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0010_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="staleness",
            field=models.DurationField(default=datetime.timedelta(0), editable=False),
        ),
    ]
