# Generated by Django 4.0.5 on 2022-07-09 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0011_profile_staleness_readonly"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="should_alert",
        ),
    ]
