# Generated by Django 5.0.3 on 2024-06-27 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0013_profile_will_alert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-last_viewed"]},
        ),
    ]
