# Generated by Django 3.2.8 on 2021-10-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0002_alter_voter_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="friends",
            field=models.ManyToManyField(blank=True, to="buddies.Voter"),
        ),
    ]
