# Generated by Django 3.2.8 on 2021-10-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0003_voter_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buddies.voter",
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="buddies.Voter"
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="ZIP code"
            ),
        ),
    ]
