# Generated by Django 3.2.8 on 2021-11-04 23:19

from django.db import migrations, models

import ballotbuddies.core.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0008_voter_voted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="slug",
            field=models.CharField(
                default=ballotbuddies.core.helpers.generate_key, max_length=100
            ),
        ),
    ]
