# Generated by Django 4.0.5 on 2022-06-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0013_voter_ballot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="ballot",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
