# Generated by Django 4.0.5 on 2022-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0015_voter_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="ballot_returned",
            field=models.DateTimeField(
                blank=True,
                help_text="Voter has returned their absentee ballot.",
                null=True,
            ),
        ),
    ]
