# Generated by Django 4.2 on 2023-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0018_voter_fetched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="status",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
