# Generated by Django 4.2.8 on 2024-01-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0019_voter_status_readonly"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="promoter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_voters",
                to="buddies.voter",
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_voters",
                to="buddies.voter",
            ),
        ),
    ]
