# Generated by Django 5.0.3 on 2024-05-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0020_voter_promoter"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="ballot_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Voter has filled out their sample ballot.",
                null=True,
            ),
        ),
    ]
