# Generated by Django 5.0.3 on 2024-07-13 01:09

from django.db import migrations, models

import ballotbuddies.core.helpers


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0022_voter_ballot_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="token",
            field=models.CharField(
                default=ballotbuddies.core.helpers.generate_key, max_length=100
            ),
        ),
    ]
