# Generated by Django 3.2.8 on 2021-10-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0005_voter_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="neighbors",
            field=models.ManyToManyField(
                blank=True, related_name="lurkers", to="friends.voter"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="strangers",
            field=models.ManyToManyField(
                blank=True, related_name="blockers", to="friends.voter"
            ),
        ),
    ]
