# Generated by Django 3.2.8 on 2021-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0007_voter_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="voted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
