# Generated by Django 4.0.3 on 2022-06-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0011_alter_voter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="absentee",
            field=models.BooleanField(
                default=True, help_text="Voter plans to vote by mail."
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voted",
            field=models.DateTimeField(
                blank=True,
                help_text="Voter has participated in the upcoming election.",
                null=True,
            ),
        ),
    ]
