# Generated by Django 4.0.6 on 2022-07-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0016_voter_ballot_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="state",
            field=models.CharField(default="", editable=False, max_length=20),
        ),
    ]
